name: Python CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy flake8 pytest

      - name: Run mypy
        run: mypy src tests
        continue-on-error: true

      - name: Run flake8
        run: flake8 src tests --extend-ignore=E203
        continue-on-error: true

      - name: Run pytest
        run: pytest
        continue-on-error: true
